// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Sales_Managment_System;

#nullable disable

namespace Sales_Managment_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251215162855_j")]
    partial class j
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sales_Managment_System.Models.DailyReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<int>("CarNumbers")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<int>("Sum")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("dailyReports");
                });

            modelBuilder.Entity("Sales_Managment_System.Models.HistoricalTransactions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("CarNumber")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Time")
                        .HasColumnType("NVARCHAR2(48)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("tr_hist");
                });

            modelBuilder.Entity("Sales_Managment_System.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("ServicePrice")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("services");
                });

            modelBuilder.Entity("Sales_Managment_System.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("CarNumber")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Time")
                        .HasColumnType("NVARCHAR2(48)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("tr_daily");
                });

            modelBuilder.Entity("Sales_Managment_System.Models.HistoricalTransactions", b =>
                {
                    b.HasOne("Sales_Managment_System.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Sales_Managment_System.Models.Transaction", b =>
                {
                    b.HasOne("Sales_Managment_System.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });
#pragma warning restore 612, 618
        }
    }
}
